<?php

namespace ContainerBcE5PvK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_46c6bPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.46c_6bP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.46c_6bP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'voyageRepository' => ['privates', 'App\\Repository\\VoyageRepository', 'getVoyageRepositoryService', true],
        ], [
            'voyageRepository' => 'App\\Repository\\VoyageRepository',
        ]);
    }
}
