<?php

namespace ContainerBcE5PvK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NDhWtnWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nDhWtnW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nDhWtnW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.bmG4G8k', 'get_ServiceLocator_BmG4G8kService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.bmG4G8k', 'get_ServiceLocator_BmG4G8kService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\UniversController::delete' => ['privates', '.service_locator.f8N1BCm', 'get_ServiceLocator_F8N1BCmService', true],
            'App\\Controller\\UniversController::edit' => ['privates', '.service_locator.f8N1BCm', 'get_ServiceLocator_F8N1BCmService', true],
            'App\\Controller\\UniversController::index' => ['privates', '.service_locator.RxrK5zZ', 'get_ServiceLocator_RxrK5zZService', true],
            'App\\Controller\\UniversController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\UniversController::show' => ['privates', '.service_locator.QgT.LbK', 'get_ServiceLocator_QgT_LbKService', true],
            'App\\Controller\\VoyageController::delete' => ['privates', '.service_locator.CYiO8Yg', 'get_ServiceLocator_CYiO8YgService', true],
            'App\\Controller\\VoyageController::edit' => ['privates', '.service_locator.CYiO8Yg', 'get_ServiceLocator_CYiO8YgService', true],
            'App\\Controller\\VoyageController::index' => ['privates', '.service_locator.46c_6bP', 'get_ServiceLocator_46c6bPService', true],
            'App\\Controller\\VoyageController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\VoyageController::show' => ['privates', '.service_locator.FriUpcQ', 'get_ServiceLocator_FriUpcQService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.bmG4G8k', 'get_ServiceLocator_BmG4G8kService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.bmG4G8k', 'get_ServiceLocator_BmG4G8kService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\UniversController:delete' => ['privates', '.service_locator.f8N1BCm', 'get_ServiceLocator_F8N1BCmService', true],
            'App\\Controller\\UniversController:edit' => ['privates', '.service_locator.f8N1BCm', 'get_ServiceLocator_F8N1BCmService', true],
            'App\\Controller\\UniversController:index' => ['privates', '.service_locator.RxrK5zZ', 'get_ServiceLocator_RxrK5zZService', true],
            'App\\Controller\\UniversController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\UniversController:show' => ['privates', '.service_locator.QgT.LbK', 'get_ServiceLocator_QgT_LbKService', true],
            'App\\Controller\\VoyageController:delete' => ['privates', '.service_locator.CYiO8Yg', 'get_ServiceLocator_CYiO8YgService', true],
            'App\\Controller\\VoyageController:edit' => ['privates', '.service_locator.CYiO8Yg', 'get_ServiceLocator_CYiO8YgService', true],
            'App\\Controller\\VoyageController:index' => ['privates', '.service_locator.46c_6bP', 'get_ServiceLocator_46c6bPService', true],
            'App\\Controller\\VoyageController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\VoyageController:show' => ['privates', '.service_locator.FriUpcQ', 'get_ServiceLocator_FriUpcQService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\UniversController::delete' => '?',
            'App\\Controller\\UniversController::edit' => '?',
            'App\\Controller\\UniversController::index' => '?',
            'App\\Controller\\UniversController::new' => '?',
            'App\\Controller\\UniversController::show' => '?',
            'App\\Controller\\VoyageController::delete' => '?',
            'App\\Controller\\VoyageController::edit' => '?',
            'App\\Controller\\VoyageController::index' => '?',
            'App\\Controller\\VoyageController::new' => '?',
            'App\\Controller\\VoyageController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\UniversController:delete' => '?',
            'App\\Controller\\UniversController:edit' => '?',
            'App\\Controller\\UniversController:index' => '?',
            'App\\Controller\\UniversController:new' => '?',
            'App\\Controller\\UniversController:show' => '?',
            'App\\Controller\\VoyageController:delete' => '?',
            'App\\Controller\\VoyageController:edit' => '?',
            'App\\Controller\\VoyageController:index' => '?',
            'App\\Controller\\VoyageController:new' => '?',
            'App\\Controller\\VoyageController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
