<?php

namespace ContainerBcE5PvK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F8N1BCmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f8N1BCm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f8N1BCm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'univer' => ['privates', '.errored..service_locator.f8N1BCm.App\\Entity\\Univers', NULL, 'Cannot autowire service ".service_locator.f8N1BCm": it references class "App\\Entity\\Univers" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'univer' => 'App\\Entity\\Univers',
        ]);
    }
}
