<?php

namespace ContainerBcE5PvK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoyage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FriUpcQ.App\Entity\Voyage' shared service.
     *
     * @return \App\Entity\Voyage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FriUpcQ": it references class "App\\Entity\\Voyage" but no such service exists.');
    }
}
