<?php

namespace Container2gxIJQM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RxrK5zZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RxrK5zZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RxrK5zZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'universRepository' => ['privates', 'App\\Repository\\UniversRepository', 'getUniversRepositoryService', true],
        ], [
            'universRepository' => 'App\\Repository\\UniversRepository',
        ]);
    }
}
