<?php

namespace Container2gxIJQM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QgT_LbKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QgT.LbK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QgT.LbK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'univer' => ['privates', '.errored..service_locator.QgT.LbK.App\\Entity\\Univers', NULL, 'Cannot autowire service ".service_locator.QgT.LbK": it references class "App\\Entity\\Univers" but no such service exists.'],
        ], [
            'univer' => 'App\\Entity\\Univers',
        ]);
    }
}
