<?php

namespace Container2gxIJQM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUniversTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\UniversType' shared autowired service.
     *
     * @return \App\Form\UniversType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UniversType.php';

        return $container->privates['App\\Form\\UniversType'] = new \App\Form\UniversType();
    }
}
