<?php

namespace Container2gxIJQM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnivers2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.f8N1BCm.App\Entity\Univers' shared service.
     *
     * @return \App\Entity\Univers
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.f8N1BCm": it references class "App\\Entity\\Univers" but no such service exists.');
    }
}
