<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcE5PvK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcE5PvK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBcE5PvK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBcE5PvK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBcE5PvK\App_KernelDevDebugContainer([
    'container.build_hash' => 'BcE5PvK',
    'container.build_id' => '9dbb4b11',
    'container.build_time' => 1643111471,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBcE5PvK');
